In [41]:
import numpy as np
import pandas as pd
import sklearn
import seaborn as sns
import matplotlib.pyplot as plt

In [42]:
%matplotlib inline

In [43]:
docs=pd.read_csv('example_train1.csv')

In [44]:
docs.head()

Document      Class
0         Teclov is a great educational institution.  education
1            Educational greatness depends on ethics  education
2  A story of great ethics and educational greatness  education
3                           Sholey is a great cinema     cinema
4                   good movie depends on good story     cinema

In [45]:
docs['Class']=docs.Class.map({'cinema':0,'education':1})
docs

Document  Class
0         Teclov is a great educational institution.      1
1            Educational greatness depends on ethics      1
2  A story of great ethics and educational greatness      1
3                           Sholey is a great cinema      0
4                   good movie depends on good story      0

In [46]:
numpy_array=docs.to_numpy()
x=numpy_array[:,0]
y=numpy_array[:,1].astype(int)
print('x')
print(x)
print('y')
print(y)
y.dtype

x
['Teclov is a great educational institution.'
 'Educational greatness depends on ethics'
 'A story of great ethics and educational greatness'
 'Sholey is a great cinema' 'good movie depends on good story']
y
[1 1 1 0 0]


dtype('int32')

In [47]:
from sklearn.feature_extraction.text import CountVectorizer

In [48]:
vec=CountVectorizer()

In [49]:
vec.fit(x)

CountVectorizer()

In [50]:
vec.vocabulary_

{'teclov': 15,
 'is': 9,
 'great': 6,
 'educational': 3,
 'institution': 8,
 'greatness': 7,
 'depends': 2,
 'on': 12,
 'ethics': 4,
 'story': 14,
 'of': 11,
 'and': 0,
 'sholey': 13,
 'cinema': 1,
 'good': 5,
 'movie': 10}

In [51]:
vec=CountVectorizer(stop_words='english')
vec.fit(x)
vec.vocabulary_

{'teclov': 11,
 'great': 5,
 'educational': 2,
 'institution': 7,
 'greatness': 6,
 'depends': 1,
 'ethics': 3,
 'story': 10,
 'sholey': 9,
 'cinema': 0,
 'good': 4,
 'movie': 8}

In [52]:
print(vec.get_feature_names())

['cinema', 'depends', 'educational', 'ethics', 'good', 'great', 'greatness', 'institution', 'movie', 'sholey', 'story', 'teclov']


In [53]:
print(len(vec.get_feature_names()))

12


In [54]:
x_transformed=vec.transform(x)

In [55]:
print(x_transformed)

  (0, 2)	1
  (0, 5)	1
  (0, 7)	1
  (0, 11)	1
  (1, 1)	1
  (1, 2)	1
  (1, 3)	1
  (1, 6)	1
  (2, 2)	1
  (2, 3)	1
  (2, 5)	1
  (2, 6)	1
  (2, 10)	1
  (3, 0)	1
  (3, 5)	1
  (3, 9)	1
  (4, 1)	1
  (4, 4)	2
  (4, 8)	1
  (4, 10)	1


In [56]:
x=x_transformed.toarray()

In [57]:
x

array([[0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1],
       [0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 2, 0, 0, 0, 1, 0, 1, 0]], dtype=int64)

In [58]:
pd.DataFrame(x, columns=vec.get_feature_names())

cinema  depends  educational  ethics  good  great  greatness  institution  \
0       0        0            1       0     0      1          0            1   
1       0        1            1       1     0      0          1            0   
2       0        0            1       1     0      1          1            0   
3       1        0            0       0     0      1          0            0   
4       0        1            0       0     2      0          0            0   

   movie  sholey  story  teclov  
0      0       0      0       1  
1      0       0      0       0  
2      0       0      1       0  
3      0       1      0       0  
4      1       0      1       0

In [59]:
test_docs=pd.read_csv('example_test.csv')

In [60]:
test_docs

Document      Class
0  very good educational institution  education

In [61]:
test_docs['Class']=test_docs.Class.map({'cinema':0, 'education':1})
test_docs

Document  Class
0  very good educational institution      1

In [62]:
test_numpy_array=test_docs.to_numpy()

In [63]:
x_test=test_numpy_array[:,0]

In [64]:
y_test=test_numpy_array[:,1]

In [65]:
x_test

array(['very good educational institution'], dtype=object)

In [66]:
y_test

array([1], dtype=object)

In [67]:
x_test_transformed=vec.transform(x_test)

In [68]:
print(x_test_transformed)

  (0, 2)	1
  (0, 4)	1
  (0, 7)	1


In [69]:
x_test=x_test_transformed.toarray()

In [70]:
x_test

array([[0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0]], dtype=int64)

In [71]:
from sklearn.naive_bayes import MultinomialNB

In [72]:
mnb=MultinomialNB()

In [73]:
type(y)

numpy.ndarray

In [74]:
mnb.fit(x,y)

MultinomialNB()

In [75]:
mnb.predict_proba(x_test)

array([[0.32808399, 0.67191601]])

In [76]:
proba=mnb.predict_proba(x_test)
print('prob class cinema', proba[:,0])
print('prob class edu', proba[:,1])

prob class cinema [0.32808399]
prob class edu [0.67191601]


In [77]:
pd.DataFrame(proba, columns=['cinema','education'])

cinema  education
0  0.328084   0.671916

In [78]:
from sklearn.naive_bayes import BernoulliNB

In [80]:
bnb=BernoulliNB()

In [81]:
bnb.fit(x,y)

BernoulliNB()

In [85]:
proba_bnb=bnb.predict_proba(x_test)

In [86]:
pd.DataFrame(proba_bnb, columns=['cinema','education'])

cinema  education
0  0.232637   0.767363